User
yrk06/TapTakeE-Sports pull request #2
Opened 2022-10-07 14:25 UTC by gabrielscholze-r

2022-10-07 14:35 UTC, yrk06 approved these changes
👍

2022-10-07 23:29 UTC, yrk06 requested changes

2022-10-07 23:29 UTC, yrk06 commented on backend/src/main/java/com/taptake/backend/controller/UserController.java
> +    public ResponseEntity<Object> updateOne(@RequestBody UserDTO userDTO, @RequestParam("emal") String email){
```suggestion
    public ResponseEntity<Object> updateOne(@RequestBody UserDTO userDTO, @RequestParam("email") String email){
```
Fix the name

2022-10-08 00:02 UTC, AlexCohenDambros approved these changes

2022-10-08 00:03 UTC, yrk06 approved these changes

2022-10-08 00:03 UTC, merged

2022-10-13 13:31 UTC, yrk06 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cadastrar Usuario](https://trello.com/c/17p9dQnN/29-cadastrar-usuario)